spring:
  datasource:
    url: jdbc:mysql://localhost/salud_vital_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${DB_PSWCAC}


 ## spring.datasource.url=jdbc:h2:mem:testdb
 ##spring.datasource.driverClassName=org.h2.Driver
 ## spring.datasource.username=sa
##spring.datasource.password=password
## spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
