spring:
  profile.active: default
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    #username: root
    username: ${DB_NAME}
    #password: ${DB_PSWCAC}  # Variable de entorno para la contraseña de la DB
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CORS_ALLOWED_ORIGINS}  # Variable de entorno CORS para issuer-uri

server:
  error:
    include-stacktrace: never

#api:
 # security:
  #  secret: ${JWT_SECRET:123456}  # Variable de entorno para JWT secret con valor por defecto

auth0:
  domain: ${DOMAIN_AUTH0}
  audience: ${AUTH0_AUDIENCE}  # Variable de entorno para el audience de Auth0

flyway:
  enabled: true
  locations: classpath:/db/migration
  schemas: railway

web:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}  # Variable de entorno CORS_ALLOWED_ORIGINS

#spring.datasource.url=jdbc:mysql://localhost/salud_vital
#spring.datasource.username=root
#spring.datasource.password=2812
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.error.include-stacktrace=never
#
#api.security.secret=${JWT_SECRET:123456}

