spring:
  profile.active: prod
  datasource:
    url: ${DATASOURCE_URL}
    username: root
    password: ${DB_PSWCAC}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}


